### ISSUE TITLE
chap 3..slot implementation in rasa 3x

### ISSUE THREAD

**Issue by caprone** [PacktPublishing/Conversational-AI-with-RASA#2]
HI
query_date intent for Rasa 3, You need add mappings

slots:
  date:
    type: text
    influence_conversation: false
    mappings:
      - type: from_entity
        entity: date

**Comment by howl-anderson** [comment]
Hi @caprone, thanks for your feedback. The problem you mentioned does exist in Rasa 3.0, but the book is for Rasa 2.0, so technically it's not a problem. But as Rasa 3.0 is developing rapidly and maturing, the author team is planning to publish the second edition of this book for Rasa 3.0, so stay tuned.
