### ISSUE TITLE
Chapter 6 - no slot mappings for Rasa 3

### ISSUE THREAD

**Issue by ecsricktorzynski** [PacktPublishing/Conversational-AI-with-RASA#3]
Similarly to https://github.com/PacktPublishing/Conversational-AI-with-RASA/issues/2, slot mappings are needed for chapter 6 example for Rasa 3x.

**Comment by howl-anderson** [comment]
Hi @ecsricktorzynski, thanks for your feedback. This issue does not affect the book which is developed for Rasa 2.0, but we plan to upgrade the book to support Rasa 3.0, so stay tuned.
